title: Yuyu Lai

logo: samsung.jpg  

description: Data Engineer

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: yuyulai022@gmail.com # Allow visitors to contact you
